---
sudo: required
language: c
dist: xenial

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8
      env:
        - MATRIX_EVAL="CC=gcc-8"

before_install:
  - eval "${MATRIX_EVAL}"
  - sudo apt-get update; sudo apt-get install check

install:
  - autoreconf -vfi
  - ./configure && make && make check
