---
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-9
      env:
        - MATRIX_EVAL="CC=gcc-9"

before_install:
  - eval "${MATRIX_EVAL}"

language: c
dist: xenial

install:
  - autoreconf -vfi
  - ./configure && make && make check
